### ISSUE TITLE
Astro Command Center or Microsoft Accessory Center can't detect their headsets when HidHide is just installed

### ISSUE THREAD

**Issue by AleksRacing** [nefarius/HidHide#108]
### Bug description
Once the HidHide is just installed, even without configuration and not changing any settings, Astro Command Center or Microsoft Accessory Center can't detect headsets. Headsets are not hidden and visible in the system, work well. But it is impossible to manage any headset settings. The issue is reproduced 100% even after clean Windows install. On Desktop PC and a laptop.

### Steps to reproduce
- Install Astro Command Center from Microsoft Store, open it and make sure connected headset is detected and its settings are available to change. Reproduced with Astro A50 Wireless Gaming Headset Gen 3. Or Install Microsoft Accessory Center from Microsoft Store and check the same. Reproduced with Microsoft Modern Wireless Headset.
- Install HidHide v1.2.98 and reboot PC.
- Open Astro Command Center or Microsoft Accessory Center.

**Actual result:** Software displays message: headset is not connected.
**Expected result:** Headset should be visible in mentioned software and its settings should be available.

### Machine info
**CPU-Architecture:** x86
**Windows version:** Windows 11 22H2
**Software/driver version(s):** v1.2.98

### Any other helpful information
Uninstalling HidHide does not make the software detect headsets again.

Update 5/4/2023. Before steps to reproduce the ViGEmBus driver 1.21.442 was installed. It was installed right from DS4Windows as well as the HidHide driver. I was faced with this issue at least couple of years ago, but only now I was able to identify what causes it.

**Comment by nefarius** [comment]
> Uninstalling HidHide does not make the software detect headsets again.

Odd, you uninstalled with the setup or some manual intervention?

**Comment by nefarius** [comment]
> **CPU-Architecture:** x86

There is no 32-Bit build of HidHide so I highly doubt this claim 😉

**Comment by AleksRacing** [comment]
> There is no 32-Bit build of HidHide so I highly doubt this claim 😉
As I understand, any modern CPU for Desktop PCs and laptops, that can run regular Windows is x86 architecture. My CPU is the Intel Core i7-9700k.

**Comment by nefarius** [comment]
Can't reproduce.
