### ISSUE TITLE
Enable Device Hiding does not stay on

### ISSUE THREAD

**Issue by gmartins-henrique** [nefarius/HidHide#114]
For some reason, the Enable Device Hiding option on the device tab does not stay on, after restarts.

I'm Using Handheld Companion and it did Auto Install a version of HidHide, that works for a couple of days and then it stops.

But after it stops working, even If I uninstall HC, and HidHide, and reinstall just HidHide, it still won't stay on, I would have to  open the HidHid settings, and enable device hiding.

**Comment by nefarius** [comment]
Without a single thing provided to investigate this bug report is unfortunately completely useless.

**Comment by nefarius** [comment]
HideHide doesn't disable itself, check what other software you're using that interfaces with HH.
