### ISSUE TITLE
HIDHide Watchdog taking up large amounts of RAM

### ISSUE THREAD

**Issue by rhobiusvoid** [nefarius/HidHide#126]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read [the project documentation](https://docs.nefarius.at/projects/) and not found a solution to my problem there
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

The Watchdog service that ensures the configs are set properly between updates or system changes is taking huge proportions of RAM, upwards of 300MB.

### Steps to reproduce

- Unsure how to reproduce this, or what the actual environment for it is, but the watchdog service just seems to keep growing in RAM usage until the user notices and terminates it, letting it start over again.

**Actual result:** Letting it run over time will just keep growing its RAM usage, likely as a result of some memory leak.
**Expected result:** Should just stay reasonable.

### Screenshots

Would've posted one if I hadn't terminated it. Sorry.

### Machine info

**CPU-Architecture:** x64
**Windows version:** Windows 10 LTSC 21H2
**Software/driver version(s):** Latest one, part of security bulletin, legacinated

### Any other helpful information

n/a

**Comment by nefarius** [comment]
Uh oh. Do you have a relative feeling how long it ran until you noticed? What was the amount, roughly?

**Comment by rhobiusvoid** [comment]
I actually saw it a few days ago, where it was 500MB in RAM, but I thought nothing of it and just simply terminated it. Did a few restarts from then till here cuz of drivers for some dumb camera that didn't end up working, and I decided to peek into task manager cuz something wasn't right with another program, and that's where I saw the Watchdog service at 300MB. I only booted up my PC just an hour ago so the memleak is likely fast. I've since disabled the service, since I've completely disabled Windows Update anyways, but I've re-enabled it for now and I'm just steadily watching it.

**Comment by nefarius** [comment]
Yeah I can reproduce it, something isn't get cleaned up properly:

![image](https://github.com/nefarius/HidHide/assets/286631/f66ef1a2-a807-4be0-9e41-0043e9bc0aba)

I'll look into it. Curious, the service is not awfully complex, wonder what the culprit is.

**Comment by rhobiusvoid** [comment]
Well, good to see that it was at least reproducible, would've been a nightmare if it was my system that caused it.

**Comment by nefarius** [comment]
I'll check `util::HasDeviceClassFilter` this is the most likely culprit since we do not leak handles and this function does allocate strings.

**Comment by rhobiusvoid** [comment]
Gotcha. On my end, it's just steadily increasing in kilobytes every few seconds, similar to your reproduction of it. 
![image](https://github.com/nefarius/HidHide/assets/22803374/b54642c7-60a5-402e-a3e4-235970350fdc)

**Comment by nefarius** [comment]
Yeah the thread runs its checks every 5 seconds.

**Comment by nefarius** [comment]
> I'll check `util::HasDeviceClassFilter` this is the most likely culprit since we do not leak handles and this function does allocate strings.

Interesting, that function is innocent, I removed it and ramped up the polling rate, still leaks:

![image](https://github.com/nefarius/HidHide/assets/286631/f80f90e3-4d71-4980-b87c-6ec6cbe6414d)

**Comment by rhobiusvoid** [comment]
and it's leaking even faster

**Comment by nefarius** [comment]
> and it's leaking even faster

Because I changed 5 seconds to 50 milliseconds 😉

**Comment by nefarius** [comment]
Yep, `CheckServiceStatus` is at fault. Now to figure out why.

**Comment by nefarius** [comment]
Found and fixed it! Thanks for reporting! Next release will contain the fixed version.

**Comment by rhobiusvoid** [comment]
nicely done, and good to hear!

**Comment by nefarius** [comment]
Looking good now:

![image](https://github.com/nefarius/HidHide/assets/286631/3ebc9a69-b01a-4429-9aff-6cd1a88fb831)

**Comment by nefarius** [comment]
@rhobiusvoid could you test this new build pls before I make a release, thanks: [HidHide_1.4.192_x64.exe.zip](https://github.com/nefarius/HidHide/files/13328463/HidHide_1.4.192_x64.exe.zip)

**Comment by rhobiusvoid** [comment]
Left it running for a good half hour or so, but it only occasionally rises by like 4KB at a very slow rate. Likely just my system at this point and nothing major.
![image](https://github.com/nefarius/HidHide/assets/22803374/2312bc6e-767c-4331-904f-ded8036781ff)
