### ISSUE TITLE
What are the HidHide XBOX and XNA components in the installer for?

### ISSUE THREAD

**Issue by Filoppi** [nefarius/HidHide#134]
https://github.com/nefarius/HidHide/blob/8c58521e18a5e4d182ddbe580920cf18482ed1ac/Setup/HidHide.aip#L70

It would be nice to get a description in the installer. I was going to open a PR with the change myself but I couldn't figure out what they are for by looking at the source code :).
Thanks.

**Comment by nefarius** [comment]
Those are actually residue from earlier experiments and can be removed entirely. They were an attempt to automate class filter installation and removal via INFs entirely which would avoid the necessity of a 3rd party tool, however in my experiments this was highly volatile and didn't work reliably between Windows versions so I ditched that approach. Nowadays my [nefcon](https://github.com/nefarius/nefcon) tool does this job reliably.

Thanks for bringing it to my attention, these files can be removed as they serve no purpose on the users' machine.
