### ISSUE TITLE
Updater keeps poping up while newest Version is already installed

### ISSUE THREAD

**Issue by Eden333** [nefarius/HidHide#137]
### Bug description

Updater keeps saying, that there is an Update, while the same Version is already installed.
Happend already 3x times.

### Steps to reproduce

- starting my PC, it keeps poping up

### Screenshots

![image](https://github.com/nefarius/HidHide/assets/18154402/e6d463b4-6974-4220-9daf-56bcf1eb109f)
![image](https://github.com/nefarius/HidHide/assets/18154402/6792b4ed-4843-4d85-96a7-fc9170f82ee1)

### Machine info

**CPU-Architecture:** x64
**Windows version:** Windows 10 22H2
**Software/driver version(s):** 1.4.202

**Comment by thexile** [comment]
I suspect it is due to HidHide.sys still being 1.4.181.

![image](https://github.com/nefarius/HidHide/assets/7766368/bb14360c-b6dc-4997-9060-03b56b34272f)

**Comment by nefarius** [comment]
Nope, the updater is supposed to check against the `Version` value in `HKEY_LOCAL_MACHINE\SOFTWARE\Nefarius Software Solutions e.U.\HidHide`

**Comment by Eden333** [comment]
here is my registry entry, its also showing the newest release
![image](https://github.com/nefarius/HidHide/assets/18154402/ae9c101b-6da2-407d-a625-e6ffccb8eb66)

**Comment by nefarius** [comment]
*Looks* correct, hm, oh well. I am done diagnosing weird and unexplainable nonsense of Advanced Installer components. I am almost done with my updater replacement, needs a couple more days, then I can give you a new release. In the meantime you can get rid of the popup by disabling the `HidHide_Updater` scheduled task:

![image](https://github.com/nefarius/HidHide/assets/286631/8eb3cb53-db71-4849-a587-ab2fa7576ca1)

**Comment by mbc07** [comment]
I'm having the same issue. Just did a full uninstall and then reinstalled the same version it keeps asking me to update to, and yep, the updater still appears saying a new update is available...

**Comment by nefarius** [comment]
Welp, see my last post.

**Comment by nefarius** [comment]
@Eden333 can you please try this one http://sharex.nefarius.at/u/HidHide_1.5.212_x64.exe and give feedback.

**Comment by QwerkyPengwen** [comment]
> @Eden333 can you please try this one http://sharex.nefarius.at/u/HidHide_1.5.212_x64.exe and give feedback.

have done testing with this installed and it indeed doesn't pop up saying it needs to update anymore.

**Comment by thexile** [comment]
Looking great!
![image](https://github.com/nefarius/HidHide/assets/7766368/aeaeb161-aec4-4472-af28-073622395069)

**Comment by nefarius** [comment]
Excellent, we're getting somewhere, first step to replace AI is a success then, I'll prepare an official release soon.

**Comment by ionzxp** [comment]
I just did my research about this. for some reason, the current updater try to read version from `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Nefarius Software Solutions e.U.\HidHide` which doesn't exist.
![image](https://github.com/nefarius/HidHide/assets/62094227/9bbbd808-f853-410f-a21d-c339175f8a66)

copy values from `HKEY_LOCAL_MACHINE\SOFTWARE\Nefarius Software Solutions e.U.\HidHide` to the key above fixed the issue.

**Comment by nefarius** [comment]
> I just did my research about this. for some reason, the current updater try to read version from `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Nefarius Software Solutions e.U.\HidHide` which doesn't exist. ![image](https://private-user-images.githubusercontent.com/62094227/304843917-9bbbd808-f853-410f-a21d-c339175f8a66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5Mzg0OTMsIm5iZiI6MTcwNzkzODE5MywicGF0aCI6Ii82MjA5NDIyNy8zMDQ4NDM5MTctOWJiYmQ4MDgtZjg1My00MTBmLWEyMWQtYzMzOTE3NWY4YTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDE5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhY2U2MWQ0MmQ5MzlhOTVkMjYzMmNlMTIxNDJhZTllZDgyYmIyNzA1ZjM2M2JjNjA0Y2Q1NmExMDJiOWFmZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x9AxoTsTfYiIzG7vjufID9FaJoEDfB0Wv94nwULSy8s)
> 
> copy values from `HKEY_LOCAL_MACHINE\SOFTWARE\Nefarius Software Solutions e.U.\HidHide` to the key above fixed the issue.

Sounds like follows: the AI updater binary is a 32-Bit executable while HH setup and components are 64-Bit, which will end up in the normal Software key in the Registry. The updater then looks in the 32-Bit (`WOW6432Node`) on the system, can't find the entry and falls back to reporting an outstanding update.

Nonetheless, it will get replaced, and the problem will be no more 😎

**Comment by nefarius** [comment]
New version is out! No risk no fun, publishing it via old updater mechanism, so long, ya bastard! 🖖 

[No risk no fun](https://github.com/nefarius/HidHide/releases/tag/v1.5.212.0) 🤣
