### ISSUE TITLE
URGENT: All peripherals stopped working after updating hidehide last night.

### ISSUE THREAD

**Issue by dubstephen** [nefarius/HidHide#139]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read [the project documentation](https://docs.nefarius.at/projects/) and not found a solution to my problem there
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I have multiple mouse and keyboards and none of them are working immediately following the latest hidehide update. The last thing I did before turning off my PC last night was update hidehide. I'm assuming I'll have to figure out a way to fix my current issue on my own, but this HAS TO GET FIXED! Here is a reddit post from almost 2 years ago describing the exact behavior (https://www.reddit.com/r/DS4Windows/comments/u90y53/after_installing_hidhide_my_mouse_and_keyboard/).

The peripherals only work up until the windows splash screen.

I would very much like to avoid having to reinstall windows and losing all of my data because I work from home and would have a LOT of setup. I'm **_extremely_** lucky because my job is pretty chill, but this could very easily have career ending consequences for someone else. I cannot stress enough how important it is that this gets fixed.

### Steps to reproduce

- I was prompted multiple times through this week to update hidehide.
- I finally updated last night (2/7/24).
- I went through the setup wizard and selected default options.
- I was prompted to restart my PC immediately, but the box said I could select "no" and restart at a later time.
- I selected "no".
- Probably about 15 minutes later I wrapped up the call I was on and turned off my PC.
- This morning I booted up my PC to get started on work for the day and none of my peripherals worked.
- Currently stuck at the windows user sign in screen.

**Actual result:** Mouse and keyboard does not work. I tried multiples. They work in BIOS and up to the point of the windows splash screen. My guess is this is when hidehide starts up and hides my devices.
**Expected result:** Mouse and keyboard should work.

### Machine info

**CPU-Architecture:** Pretty sure it's x64.
**Windows version:** Windows 11.
**Software/driver version(s):** I assume it's the latest.

### Any other helpful information

I believe I've provided all relevant information. If I think of anything else I will provide an update.

**Comment by nefarius** [comment]
Duplicated of #131 please use the search.
