### ISSUE TITLE
An update may require 2 restarts to be applied

### ISSUE THREAD

**Issue by avi12** [nefarius/HidHide#144]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read [the project documentation](https://docs.nefarius.at/projects/) and not found a solution to my problem there
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
After the initial restart required by the first update setup, it will demand the computer to be restarted again

### Steps to reproduce
- HidHide prompts me to update it
- I click the to download the update right now
- It will open the setup wizard and install the update
- After the setup finishes, it will ask me to restart the computer

**Actual result:** After restarting, it will prompt another setup that automatically installs something and then asks me to restart the computer
**Expected result:** Should only require a single restart

### Machine info

**CPU-Architecture:** x64
**Windows version:** Windows 10 22H2
**Software/driver version(s):** 1.5.212.0

**Comment by Johnsn0w** [comment]
> That's a well known fact and on purpose, not a bug.

I suggest it would be useful to the user if this was made obvious, either initially or on the second restart prompt.
I thought it was stuck an infinite install loop so I didn't do the second restart as I'd never two-restarts-required it before.

**Comment by nefarius** [comment]
It is what it is. PRs welcome, I do not have the time for such details.

**Comment by avi12** [comment]
I became aware of your piece of software via (DSX)[https://store.steampowered.com/app/1812620/DSX/] by being recommended to install it as a quality of life feature, but IIRC it had never mentioned the need to restart the computer twice to complete an updates

**Comment by nefarius** [comment]
Anyway, this back and forth is rather pointless, anyone is welcome to start contributing and improving the software instead of relying on me for everything, that's how open source is supposed to work, closing this thread.
