### ISSUE TITLE
HidHide Will Not Update and Will Not Uninstall

### ISSUE THREAD

**Issue by dece870717** [nefarius/HidHide#146]
Current OS info

Edition	Windows 11 Pro
Version	23H2
Installed on	‎9/‎6/‎2023
OS build	22631.3235
Experience	Windows Feature Experience Pack 1000.22687.1000.0

Currently stuck on HidHide v1.4.202.

I kept getting a prompt every so often to update HidHide, I'd run it, but wouldn't read what it'd say at the end. 
![Screenshot 2024-03-10 065834](https://github.com/nefarius/HidHide/assets/112725402/cd968f9b-d00d-45a3-984d-ffede3b7bb22)

So, after seeing that I tried uninstalling it, but absolutely nothing happens, it will not uninstall! A window briefly appears that says please wait while Windows configures HidHide and then disappears, no further anything happens. Whole thing reminds me of trying to uninstall an older version of Microsoft Office from newer Windows versions, where you have to install and run Microsoft Support and Recovery Assistant, and then that will find the program and run its own unique uninstaller, the situation also makes it impossible to install a newer version of Microsoft Office. I've ran the Legacinator, which gives me 2 options, one is about outdated hidhide configuration updater, and the other is to clean/reset the application list, both options fix nothing.

I use HidHide with DSX via the steam app. I haven't had really any issues but none the less, this needs some sort of solution. Is there some special uninstaller for this? Or any commands that I need to run in PowerShell so as to be able to install the new version? I've tried to use the HidHide v1.4.202 installer to try to resolve it but all three options achieve nothing, neither Modify, Repair, or Uninstall changes anything.

**Comment by nefarius** [comment]
The setup uses Microsoft Windows Installer (MSI) under the hood, there is nothing special to it, so any search query like "how to remove broken MSI setup" in your favourite search engine could yield some success. Improper removal of HidHide can cause problems so [make sure to have this guide on stand-by](https://docs.nefarius.at/projects/HidHide/fixing-a-bricked-system/) and/or make backups before you start fiddling with things.

Good luck.

**Comment by dece870717** [comment]
> The setup uses Microsoft Windows Installer (MSI) under the hood, there is nothing special to it, so any search query like "how to remove broken MSI setup" in your favourite search engine could yield some success. Improper removal of HidHide can cause problems so [make sure to have this guide on stand-by](https://docs.nefarius.at/projects/HidHide/fixing-a-bricked-system/) and/or make backups before you start fiddling with things.
> 
> Good luck.

Funny you mentioned the guide, I ended up having to use it before I made this post. Fortunately I have TeamViewer on my PC so I could remote desktop through my phone and delete those registry entries, but after I did I couldn't get HidHide to work at all because it still wouldn't uninstall or reinstall.

What's strange is how the msi could be broken if even through the installer for the version I have can't uninstall it, all it can do is reinstall itself, but it can't uninstall itself, but I'll see what I could find to possibly help.

**Comment by dece870717** [comment]
I figured it out, had to do with my group policy setting for Powershell scripts. I had it set to only trusted publishers

**Comment by RespawnAnker** [comment]
> I figured it out, it had to do with my having contained languages set on Powershell and my group policy setting for Powershell scripts. I had it set to only trusted publishers.

Hey, i did the thing you mentioned in here but it still is refusing to install for me, if i run the .exe it puts all the files in "ProgramData" and if i move it to program files then it starts working but then it again extracts all the files in programdata and even if i try running it from programdata it either wont launch or sm else.
