### ISSUE TITLE
nProtect The program recognizes it as a keylogger.

### ISSUE THREAD

**Issue by yousamkij1** [nefarius/HidHide#147]
In Korea, if you want to pay with a credit card
You must install a security program called "nProtect" unconditionally.
It must be installed by force.
In nProtect, the HidHide program is recognized as a keylogger, so card payment is not possible on all websites.
Can't you update it so it doesn't recognize as a keylogger in "nProtect?
HidHide program is required for DSX program.

**Comment by nefarius** [comment]
I have no idea why it is detected as a Keylogger and - obviously - habe no influence over any 3rd party anti-virus and their habit for false positives. Contact the support for your AV solution, I can't do anything about this.
