### ISSUE TITLE
My computer keeps randomly crashing/restarting

### ISSUE THREAD

**Issue by maxab0** [nefarius/HidHide#148]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read [the project documentation](https://docs.nefarius.at/projects/) and not found a solution to my problem there
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

My computer will randomly crash/restart this happens most commonly while playing games. There is no pattern to the restarts.
In event viewer it is down as Event ID 22 and says,

”The event logging service encountered an error while initialising publishing resources for channel Nefarius-Drivers-HidHideClient/Diagnostic. If channel type is Analytic or Debug, then this could mean there was an error initialising logging resources as well”

### Screenshots

Everything just goes black unexpectadly takes a minute then goes to the page you see when you turn on your computer, like a restart. 

### Machine info

Processor - AMD Ryzen 5 3600 
16Gb Ram
Windows 11
Display - Nividia GeForce GTX 1660 Super

**Comment by nefarius** [comment]
What makes you think HH is at fault? Do you have a crash dump with the details who triggered the fault?

**Comment by maxab0** [comment]
I dont know what the issue is im just trying to figure out thought i could get some help

**Comment by nefarius** [comment]
Neither do I. If you open a bug report it is **your** responsibility to make a proper report with useful information, not wild guesses. Closing.
