### ISSUE TITLE
Error code 0x0003 at src\HID.cpp(282) `anonymous-namespace'::HidModelInfo: The system cannot find the path specified.

### ISSUE THREAD

**Issue by v3i1y** [nefarius/HidHide#151]
### Bug description

Cannot open device list in the configuration UI, crashes with "Something unforeseen..."

When running --dev-all with CLI client, showing error:
```
Error code 0x0003 at src\HID.cpp(282) `anonymous-namespace'::HidModelInfo: The system cannot find the path specified.
```
### Steps to reproduce

Not sure the exact cause of this as it works on my other computer.

**Comment by nefarius** [comment]
Does it also happen with [this build](http://sharex.nefarius.at/u/HidHideClient.exe)?

Cheers

**Comment by v3i1y** [comment]
OMG It worked!! I have been messing around trying to figure out what's wrong for an hour. What's the magic 😂

**Comment by nefarius** [comment]
Thanks for confirming, I need to craft a new public release ant it will be fixed for all 👍

**Comment by nefarius** [comment]
Fixed [here](https://github.com/nefarius/HidHide/commit/3328f62ae9f4caa6a226336bbbfe29d253cc7d87) btw.

**Comment by nefarius** [comment]
Published, can you please test and confirm this works: https://github.com/nefarius/HidHide/releases/download/v1.5.224.0/HidHide_1.5.224_x64.exe

**Comment by v3i1y** [comment]
> Published, can you please test and confirm this works: https://github.com/nefarius/HidHide/releases/download/v1.5.224.0/HidHide_1.5.224_x64.exe

The released version does not seem to work. One thing worth noting is that the client says it's v1.5.212.0 in the title bar even though the installer says it's 1.5.224.

**Comment by nefarius** [comment]
Gotcha, I'll look into it, thanks.

**Comment by nefarius** [comment]
@v3i1y this should do the trick http://sharex.nefarius.at/u/HidHide_1.5.230_x64.exe

**Comment by nefarius** [comment]
@Jaybooon feel free to test it as well.

**Comment by nefarius** [comment]
@v3i1y how's it going, mate?

**Comment by v3i1y** [comment]
Sorry, haven’t had a chance to try it yet will take a look tonight.

**Comment by nefarius** [comment]
I consider this fixed, closing.

**Comment by trevwestbrook119-netizen** [comment]
NOT FIXED
