### ISSUE TITLE
SteamGridDb artwork submission

### ISSUE THREAD

**Issue by binarygeek119** [nefarius/HidHide#153]
not a bug but i thought i let you know i added this app to steamgribdb.com for use in steam big picture mode.

and just wanted to share the artwork here if you wanted it at all.
![2ee5d020b7e8a31c99797b4798825dc6](https://github.com/nefarius/HidHide/assets/72405030/08d52ff5-79be-4d01-87a1-6656662a000d)
![90989ac3888b2b0d3df60e97551b8de4](https://github.com/nefarius/HidHide/assets/72405030/1f671a69-5989-4d9c-85bf-21313d8efee0)

**Comment by nefarius** [comment]
You could've simply [provided the link to it](https://www.steamgriddb.com/game/5454119) instead of having me search for it on a service I never heard of before 😛 

Thanks for sharing 👍

**Comment by binarygeek119** [comment]
sorry i should have my bad.
