### ISSUE TITLE
Feature request: Hide devices by name/regex

### ISSUE THREAD

**Issue by utkabobr** [nefarius/HidHide#166]
### Description

It would be really usefull to allow hiding devices by name instead of device id to persist changes for some buggy devices.

### Why in a first place?

I'm really tired of Razer analog keyboard, it has un-disableable hardware feature that plugs in virtual gamepad that somehow bypasses HidHide config every time PC is reboot or device is reconnected.
It should be fine to block every device with "Razer Xbox 360 Controller" in a name so keyboard HID would work just fine, but it may be useful for other devices anyway.

Thanks in advance!

**Comment by nefarius** [comment]
This would pretty much mean a rewrite/redesign, plus doing regex in a kernel driver is the biggest no-no there is (see recent CrowdStrike oopsie), so unless someone else would take on this body of work, it's not gonna get worked on.

Alternatively use the provided C# API or CLI client to make your own scripts to configure HidHide on the fly.
