### ISSUE TITLE
Possible conflict to Logitech G Hub with HidHide installed

### ISSUE THREAD

**Issue by Yuuyatails** [nefarius/HidHide#172]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read [the project documentation](https://docs.nefarius.at/projects/) and not found a solution to my problem there
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

With HidHide installed, the Logitech G Hub software cannot detect input from the Logitech peripherals, even though I have not set them to be hidden in HidHide client. Furthermore, upon reconnecting the peripherals, any additional function on the Logitech peripherals (the force feedback on the G29 racing wheel, for example) no longer works unless I restart G Hub with admin rights while the peripherals remain connected. 

The G Hub can only detect the input from the peripherals after I uninstalled HidHide, which makes me think that there is some sort of software conflict between the two.

I encounter this issue with my Logitech G29.

Oddly, the USB game controller menu in Windows and games does detect the input from the G29, but force feedback remains in an unfunctional state after reconnecting it to the PC unless I restart G Hub with admin rights.

### Steps to reproduce

- Install Hidhide and Logitech G Hub.
- Open G Hub.
- Connect the Logitech peripheral (i.e. Logitech G29).
- Click on the connected peripheral in G Hub.
- Within G Hub, create a separate profile for Desktop.
- Assign the function "Profile Cycle" to a button on the Logitech Peripherals,
- Press the assigned button on the peripheral.

**Actual result:** With HidHide installed, pressing the assigned button doesn't make G Hub to switch the profile as the G Hub app cannot detect any input from Logitech peripherals, and reconnecting the peripheral results in loss of additional functions unless G Hub is restarted with admin rights. (Albeit still not detect any input from the peripherals.)
**Expected result:** With HidHide installed, pressing the assigned button will make G Hub switch the profile to the other one, as it detects inputs from Logitech peripherals.

### Screenshots

N/A

### Machine info

**CPU-Architecture:** x86_64
**Windows version:** Windows 11 Pro 24H2
**Software/driver version(s):** 1.5.230

### Any other helpful information

N/A

**Comment by nefarius** [comment]
Without a proper investigation and bug report this can simply not be addressed, closing.
