### ISSUE TITLE
Hidhide Hides Joy2Key Keyboard Input

### ISSUE THREAD

**Issue by cyypherus** [nefarius/HidHide#175]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read [the project documentation](https://docs.nefarius.at/projects/) and not found a solution to my problem there
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

Hidhide hides virtual key presses from joy2key

### Steps to reproduce

- Install Joy2Key
- Install Hidhide
- Hide controller input
- Whitelist Joy2key & verify it receives controller input
- Attempt to use Joy2Key output in another app

**Actual result:** Joy2key key presses are hidden by hidhide. If device hiding is disabled in hidhide joy2key key presses work as expected.
**Expected result:** I think hidhide shouldn't hide virtual keyboard events - only gamepad events

### Machine info

**CPU-Architecture:** x64
**Windows version:** Windows 11 23H2
**Software/driver version(s):** 1.5.230

**Comment by nefarius** [comment]
Without a proper investigation and bug report this can simply not be addressed, closing.
